
package frontend;

import javax.swing.JFrame;
import library.records.base.IRecord;
import library.roles.AdminRole;

public class AdminRoleWindow extends javax.swing.JFrame implements Navigate {
    
    AdminRole admin;
    private final String[] columnNames;
    private Navigate parent;
    
    /**
     * Creates new form AdminRoleWindow
     */
    public AdminRoleWindow(){
        
        initComponents();
        this.admin = new AdminRole();
        this.columnNames = new String[]{"LibrarianId", "Name", "Email", "Address", "Phone Number"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addLibrarianBUTTON = new javax.swing.JButton();
        viewLibrariansBUTTON = new javax.swing.JButton();
        removeLibrarianBUTTON = new javax.swing.JButton();
        logoutBUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Role");

        addLibrarianBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        addLibrarianBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        addLibrarianBUTTON.setText("Add Librarian");
        addLibrarianBUTTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addLibrarianBUTTON.setInheritsPopupMenu(true);
        addLibrarianBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLibrarianBUTTONActionPerformed(evt);
            }
        });

        viewLibrariansBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        viewLibrariansBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        viewLibrariansBUTTON.setText("View Librarians");
        viewLibrariansBUTTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewLibrariansBUTTON.setInheritsPopupMenu(true);
        viewLibrariansBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLibrariansBUTTONActionPerformed(evt);
            }
        });

        removeLibrarianBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        removeLibrarianBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        removeLibrarianBUTTON.setText("Remove Librarian");
        removeLibrarianBUTTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeLibrarianBUTTON.setInheritsPopupMenu(true);
        removeLibrarianBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLibrarianBUTTONActionPerformed(evt);
            }
        });

        logoutBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        logoutBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        logoutBUTTON.setText("Logout");
        logoutBUTTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutBUTTON.setInheritsPopupMenu(true);
        logoutBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLibrarianBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewLibrariansBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeLibrarianBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(addLibrarianBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(viewLibrariansBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(removeLibrarianBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(logoutBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLibrarianBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLibrarianBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddLibrarianWindow addLibrarian = new AddLibrarianWindow(admin);
        addLibrarian.setParentNavigate(this);
        addLibrarian.setVisible(true);
    }//GEN-LAST:event_addLibrarianBUTTONActionPerformed

    private void viewLibrariansBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLibrariansBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        IRecord[] arrayOfLibrarianUsers = admin.getList();
        String[][] twoDArrayOfLibrarians =  new String[arrayOfLibrarianUsers.length][columnNames.length];
        for(int i=0; i<arrayOfLibrarianUsers.length; i++){
            twoDArrayOfLibrarians[i] = arrayOfLibrarianUsers[i].lineRepresentation().split(",");
        }
        ViewTableWindow viewLibrarians = new ViewTableWindow("Librarians", twoDArrayOfLibrarians, columnNames);
        viewLibrarians.setVisible(true);
        viewLibrarians.setParentNavigate(this);
    }//GEN-LAST:event_viewLibrariansBUTTONActionPerformed

    private void removeLibrarianBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLibrarianBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RemoveLibrarianWindow removeLibrarian = new RemoveLibrarianWindow(admin);
        removeLibrarian.setVisible(true);
        removeLibrarian.setParentNavigate(this);
    }//GEN-LAST:event_removeLibrarianBUTTONActionPerformed

    private void logoutBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBUTTONActionPerformed
        // TODO add your handling code here:
        admin.logout();
        this.setVisible(false);
        ((JFrame)parent).setVisible(true);
    }//GEN-LAST:event_logoutBUTTONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLibrarianBUTTON;
    private javax.swing.JButton logoutBUTTON;
    private javax.swing.JButton removeLibrarianBUTTON;
    private javax.swing.JButton viewLibrariansBUTTON;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNavigate(Navigate n) {
        this.parent = n;
    }

    @Override
    public Navigate getParentNavigate() {
        return parent;
    }
}
