package frontend;

import javax.swing.JFrame;
import library.records.base.IRecord;
import library.roles.LibrarianRole;

public class LibrarianRoleWindow extends javax.swing.JFrame implements Navigate {

    private Navigate parent;

    LibrarianRole librarian;
    private final String[] columnNamesBooks;
    private final String[] columnNamesStudentBooks;

    /**
     * Creates new form LibrarianRoleWindow
     */
    public LibrarianRoleWindow() {
        initComponents();
        this.librarian = new LibrarianRole();
        this.columnNamesBooks = new String[]{"Book Id", "Title", "Author", "Publisher", "Num Of Copies"};
        this.columnNamesStudentBooks = new String[]{"Student Id", "Books Id", "Borrow Date"};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBookBUTTON = new javax.swing.JButton();
        viewBooksBUTTON = new javax.swing.JButton();
        borrowBookBUTTON = new javax.swing.JButton();
        viewBorrowedBooksBUTTON = new javax.swing.JButton();
        returnBookBUTTON = new javax.swing.JButton();
        logoutBUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Librarian Role");

        addBookBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        addBookBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        addBookBUTTON.setText("Add Book");
        addBookBUTTON.setOpaque(true);
        addBookBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBUTTONActionPerformed(evt);
            }
        });

        viewBooksBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        viewBooksBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        viewBooksBUTTON.setText("View Books");
        viewBooksBUTTON.setOpaque(true);
        viewBooksBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBooksBUTTONActionPerformed(evt);
            }
        });

        borrowBookBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        borrowBookBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        borrowBookBUTTON.setText("Borrow Book");
        borrowBookBUTTON.setOpaque(true);
        borrowBookBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowBookBUTTONActionPerformed(evt);
            }
        });

        viewBorrowedBooksBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        viewBorrowedBooksBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        viewBorrowedBooksBUTTON.setText("View Borrowed Books");
        viewBorrowedBooksBUTTON.setOpaque(true);
        viewBorrowedBooksBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBorrowedBooksBUTTONActionPerformed(evt);
            }
        });

        returnBookBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        returnBookBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        returnBookBUTTON.setText("Return Book");
        returnBookBUTTON.setOpaque(true);
        returnBookBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookBUTTONActionPerformed(evt);
            }
        });

        logoutBUTTON.setBackground(new java.awt.Color(0, 0, 0));
        logoutBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        logoutBUTTON.setText("Logout");
        logoutBUTTON.setOpaque(true);
        logoutBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrowBookBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addBookBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBooksBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                    .addComponent(viewBorrowedBooksBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBookBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(addBookBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(viewBooksBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(borrowBookBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(viewBorrowedBooksBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(returnBookBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(logoutBUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBookBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddBookWindow addBook = new AddBookWindow(librarian);
        addBook.setVisible(true);
        addBook.setParentNavigate(this);
    }//GEN-LAST:event_addBookBUTTONActionPerformed

    private void viewBooksBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBooksBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        IRecord[] arrayOfBooks = librarian.getList();
        String[][] twoDArrayOfBooks = new String[arrayOfBooks.length][columnNamesBooks.length];
        for (int i = 0; i < arrayOfBooks.length; i++) {
            twoDArrayOfBooks[i] = arrayOfBooks[i].lineRepresentation().split(",");
        }
        ViewTableWindow viewBooks = new ViewTableWindow("Books", twoDArrayOfBooks, columnNamesBooks);
        viewBooks.setVisible(true);
        viewBooks.setParentNavigate(this);
    }//GEN-LAST:event_viewBooksBUTTONActionPerformed

    private void borrowBookBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowBookBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BorrowBookWindow borrowBook = new BorrowBookWindow(librarian);
        borrowBook.setVisible(true);
        borrowBook.setParentNavigate(this);
    }//GEN-LAST:event_borrowBookBUTTONActionPerformed

    private void viewBorrowedBooksBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBorrowedBooksBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        IRecord[] arrayOfStudentBooks = librarian.getListOfBorrowingOperations();
        String[][] twoDArrayOfStudentBooks = new String[arrayOfStudentBooks.length][columnNamesStudentBooks.length];
        for (int i = 0; i < arrayOfStudentBooks.length; i++) {
            twoDArrayOfStudentBooks[i] = arrayOfStudentBooks[i].lineRepresentation().split(",");
        }
        ViewTableWindow viewBorrowedBooks = new ViewTableWindow("Borrowed Books", twoDArrayOfStudentBooks, columnNamesStudentBooks);
        viewBorrowedBooks.setVisible(true);
        viewBorrowedBooks.setParentNavigate(this);
    }//GEN-LAST:event_viewBorrowedBooksBUTTONActionPerformed

    private void returnBookBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookBUTTONActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ReturnBookWindow returnBook = new ReturnBookWindow(librarian);
        returnBook.setVisible(true);
        returnBook.setParentNavigate(this);
    }//GEN-LAST:event_returnBookBUTTONActionPerformed

    private void logoutBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBUTTONActionPerformed
        // TODO add your handling code here:
        librarian.logout();
        this.setVisible(false);
        ((JFrame)parent).setVisible(true);
    }//GEN-LAST:event_logoutBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LibrarianRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LibrarianRoleWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookBUTTON;
    private javax.swing.JButton borrowBookBUTTON;
    private javax.swing.JButton logoutBUTTON;
    private javax.swing.JButton returnBookBUTTON;
    private javax.swing.JButton viewBooksBUTTON;
    private javax.swing.JButton viewBorrowedBooksBUTTON;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setParentNavigate(Navigate n) {
        this.parent = n;
    }

    @Override
    public Navigate getParentNavigate() {
        return parent;
    }
}
